### ISSUE TITLE
Javascript Problem 

### ISSUE THREAD

**Issue by mohammedawez** [Jay-study-nildana/FrontEndForStudents#38] opened 2023-08-26 12:42 UTC
hlo jay sir....!
@Jay-study-nildana 

 i m facing with some issue in javascript code can u please solve , unable to see output in console .
error displayed as :-Uncaught ReferenceError: set is not defined

here is the file repositve file code link  :-
https://github.com/mohammedawez/problem-of-javascript

url:-
https://github.com/mohammedawez/problem-of-javascript.git

@Jay-study-nildana

**Comment by Jay-study-nildana** [comment] 2023-08-28 05:33
This is a duplicate of 

https://github.com/Jay-study-nildana/FrontEndForStudents/discussions/37

so closing this. Discussion continues in 37. 

Jay

**Closed by Jay-study-nildana** 2023-08-28 05:33 UTC
